### ISSUE TITLE
Unable to get package working on debian 11: `GLIBC_2.29' not found ...

### ISSUE THREAD

**Issue by scramatte** [php-opencv/php-opencv-packages#2]
Hi,

I've tried to install your debian packages on debian 11 (bullseye) and php 8.0.10

`PHP Warning:  PHP Startup: Unable to load dynamic library 'opencv.so' (tried: /usr/lib/php/20200930/opencv.so (/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/lib/libopencv_face.so.4.5)), /usr/lib/php/20200930/opencv.so.so (/usr/lib/php/20200930/opencv.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0`

How can we fix it?
Moreover it would be nice to publish "debian" folder to be able to rebuild the packages

Thank you

**Comment by morozovsk** [comment]
hi. try to install from sources:
https://github.com/php-opencv/php-opencv/wiki/Installation.-php-opencv#installation-on-ubuntu-2010-php-80-from-sources

**Comment by scramatte** [comment]
Sorry for the noise ... my base system was debian 10  ... I've just upgraded to debian 11 and now it works.
About the packages can you create a repository for them with reprepro for example?
Thank you
